# Generated by Django 5.1 on 2024-09-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/images'),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
