# Generated by Django 5.1 on 2024-09-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='product/images', width_field='width_field'),
        ),
    ]
