# Generated by Django 5.1 on 2024-09-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_height_field_listing_width_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
