# Generated by Django 5.1 on 2024-09-16 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='wishlist',
            field=models.ManyToManyField(null=True, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
