# Generated by Django 5.1 on 2024-09-17 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_rename_user_comment_users_alter_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Users',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='Users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments', to='auctions.comment'),
        ),
    ]
