# Generated by Django 5.1 on 2024-09-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_comment_users_remove_listing_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='list_comments', to='auctions.comment'),
        ),
    ]
